name: sfun
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_1100_select=0.0.1=gpu
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.1=py36_0
  - astor=0.8.0=py36_0
  - backports=1.0=py_2
  - backports.weakref=1.0rc1=py36_0
  - bleach=1.5.0=py36_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py36_1
  - cloudpickle=1.2.1=py_0
  - cudatoolkit=8.0=3
  - cudnn=7.1.3=cuda8.0_0
  - cupti=8.0.61=0
  - cytoolz=0.10.0=py36h7b6447c_0
  - dask-core=2.2.0=py_0
  - decorator=4.4.0=py36_1
  - gast=0.2.2=py36_0
  - google-pasta=0.1.7=py_0
  - html5lib=0.9999999=py36_0
  - imageio=2.5.0=py36_0
  - intel-openmp=2019.4=243
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py36_0
  - keras-gpu=2.2.4=0
  - keras-preprocessing=1.1.0=py_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libprotobuf=3.8.0=hd408876_0
  - libtiff=4.0.10=h2733197_2
  - markdown=3.1.1=py36_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py36h7b6447c_0
  - mock=3.0.5=py36_0
  - networkx=2.3=py_0
  - olefile=0.46=py36_0
  - openssl=1.1.1=h7b6447c_0
  - pandas=0.25.0=py36he6710b0_0
  - pillow=6.1.0=py36h34e0f95_0
  - protobuf=3.8.0=py36he6710b0_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.1=py_0
  - pywavelets=1.0.3=py36hdd07704_1
  - pyyaml=5.1.1=py36h7b6447c_0
  - scikit-image=0.15.0=py36he6710b0_0
  - six=1.12.0=py36_0
  - tensorboard=1.10.0=py36hf484d3e_0
  - tensorflow=1.10.0=gpu_py36h8dbd23f_0
  - tensorflow-base=1.10.0=gpu_py36h3435052_0
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.10.0=hf154084_0
  - termcolor=1.1.0=py36_1
  - toolz=0.10.0=py_0
  - werkzeug=0.15.4=py_0
  - wrapt=1.11.2=py36h7b6447c_0
  - yaml=0.1.7=h96e3832_1
  - zstd=1.3.7=h0b5b093_0
  - blas=2.11=openblas
  - bzip2=1.0.8=h516909a_0
  - cairo=1.16.0=hfb77d84_1002
  - cycler=0.10.0=py_1
  - dbus=1.13.6=he372182_0
  - expat=2.2.5=he1b5a44_1003
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.9=h516909a_0
  - glib=2.58.3=h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.9.0=nompi_py36h513d04c_1104
  - harfbuzz=2.4.0=h9f30f68_2
  - hdf5=1.10.5=nompi_h3c11f04_1100
  - icu=64.2=he1b5a44_0
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py36hc9558a2_0
  - lame=3.100=h14c3975_1001
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=11_openblas
  - liblapacke=3.8.0=11_openblas
  - libopenblas=0.3.6=h6e990d7_6
  - libpng=1.6.37=hed695b0_0
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h576950b_1
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hee79883_2
  - matplotlib=3.1.1=py36_1
  - matplotlib-base=3.1.1=py36he7580a8_1
  - mkl_fft=1.0.14=py36h516909a_1
  - mkl_random=1.0.4=py36hf2d7682_0
  - nettle=3.4.1=h1bed415_1002
  - opencv=4.1.1=py36ha799480_1
  - openh264=1.8.0=hdbcaa40_1000
  - pcre=8.41=hf484d3e_1003
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h14c3975_1001
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36hcca6a23_2
  - qt=5.9.7=h0c104cb_3
  - scipy=1.3.1=py36h921218d_0
  - sip=4.19.8=py36hf484d3e_1000
  - tk=8.6.9=hed695b0_1002
  - tornado=6.0.3=py36h516909a_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - _libgcc_mutex=0.1=main
  - grpcio=1.16.1=py36hf8bcb03_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.4=py36h99e49ec_0
  - numpy-base=1.16.4=py36h2f8d375_0
  - pip=19.1.1=py36_0
  - python=3.6.8=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py36_0
  - sqlite=3.29.0=h7b6447c_0
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - dask==2.2.0
    - keras==2.2.4

